# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--memory", 2048]
  end

  config.vm.box = "ubuntu/trusty64"
  config.vm.provision "shell", path: "bootstrap.sh"
  config.vm.provision "docker" do |d|
    d.run "karlpatrikbergman/jenkins-server",
      args: "-d -p 0.0.0.0:8080:8080"
  end

  config.vm.network :forwarded_port, host: 8080, guest: 8080

end